// src/lib/enquiry-data.js
// Mock enquiry tickets — customers and vendors contacting support via
// email or voicemail with questions, requests, and business inquiries.

export const MOCK_ENQUIRIES = [
  {
    id: 'ENQ-1001',
    senderType: 'customer',
    channel: 'email',
    status: 'open',
    priority: 'high',
    created: '2025-03-05T09:14:00',
    updated: '2025-03-05T09:14:00',
    subject: 'Where is my order? No tracking update in 6 days',
    preview: "Hi, I placed order #88432 on Feb 27th and tracking hasn't updated since March 1st. The package shows 'In Transit' but nothing has moved. My daughter's birthday is March 8th — I really need to know if this will arrive in time.",
    sender: {
      name: 'Rachel Torres',
      email: 'rachel.torres@gmail.com',
      phone: null,
      type: 'customer',
      tier: 'Gold',
      ltv: '$3,210',
      totalOrders: 28,
    },
    intent: 'order_status',
    intentLabel: 'Order Status',
    urgency: 4,
    sentiment: 'anxious',
    sentimentScore: -0.61,
    tags: ['shipping', 'time-sensitive', 'vip'],
    orderRef: '#88432',
    assignedTo: null,
    resolution: null,
    aiAnalysis: null,
  },
  {
    id: 'ENQ-1002',
    senderType: 'vendor',
    channel: 'email',
    status: 'open',
    priority: 'medium',
    created: '2025-03-05T08:30:00',
    updated: '2025-03-05T08:30:00',
    subject: 'Bulk purchase inquiry — 500 units of SKU #ARC-7721',
    preview: "Hello, I'm the procurement manager at Westfield Corporate Supplies. We're interested in placing a bulk order of 500 units of your SKU #ARC-7721 for corporate gifting. Can you provide volume pricing, lead time, and whether white-label packaging is available?",
    sender: {
      name: 'Daniel Marsh',
      email: 'dmarsh@westfieldcorp.com',
      phone: '+1 (312) 555-0192',
      type: 'vendor',
      company: 'Westfield Corporate Supplies',
      tier: null,
      ltv: null,
      totalOrders: 0,
    },
    intent: 'bulk_order_inquiry',
    intentLabel: 'Bulk Order Inquiry',
    urgency: 3,
    sentiment: 'neutral',
    sentimentScore: 0.1,
    tags: ['vendor', 'bulk', 'B2B', 'high-value'],
    orderRef: null,
    assignedTo: null,
    resolution: null,
    aiAnalysis: null,
  },
  {
    id: 'ENQ-1003',
    senderType: 'customer',
    channel: 'voicemail',
    status: 'open',
    priority: 'critical',
    created: '2025-03-05T07:55:00',
    updated: '2025-03-05T07:55:00',
    subject: 'Voicemail: Unauthorized charge of $189 on my account',
    preview: "[Voicemail transcript] Hi this is Marcus Webb, customer number 4421. I'm calling because I just got a notification of a $189 charge on my card from Arcella and I did not authorize this. I haven't placed any orders this month. I need someone to call me back urgently or I'm going to dispute this with my bank. My number is 917-555-0188.",
    sender: {
      name: 'Marcus Webb',
      email: 'marcus.webb@outlook.com',
      phone: '+1 (917) 555-0188',
      type: 'customer',
      tier: 'Silver',
      ltv: '$890',
      totalOrders: 9,
    },
    intent: 'billing_dispute',
    intentLabel: 'Billing Dispute',
    urgency: 5,
    sentiment: 'frustrated',
    sentimentScore: -0.88,
    tags: ['billing', 'chargeback-risk', 'urgent', 'escalation-required'],
    orderRef: null,
    assignedTo: null,
    resolution: null,
    aiAnalysis: null,
    escalationSignals: ['chargeback', 'unauthorized_charge'],
  },
  {
    id: 'ENQ-1004',
    senderType: 'vendor',
    channel: 'email',
    status: 'in_progress',
    priority: 'medium',
    created: '2025-03-04T15:20:00',
    updated: '2025-03-04T16:45:00',
    subject: 'Vendor onboarding — new supplier application',
    preview: "Dear Arcella team, I represent NovaPack Solutions, a packaging manufacturer based in Chicago. We specialize in sustainable packaging and have worked with retailers including Target and Costco. We'd like to apply to become an approved Arcella supplier. Could you direct us to the vendor onboarding process?",
    sender: {
      name: 'Priya Nair',
      email: 'p.nair@novapacksolutions.com',
      phone: '+1 (773) 555-0241',
      type: 'vendor',
      company: 'NovaPack Solutions',
      tier: null,
      ltv: null,
      totalOrders: 0,
    },
    intent: 'vendor_onboarding',
    intentLabel: 'Vendor Onboarding',
    urgency: 2,
    sentiment: 'neutral',
    sentimentScore: 0.2,
    tags: ['vendor', 'onboarding', 'new-supplier'],
    orderRef: null,
    assignedTo: 'Ravi P.',
    resolution: null,
    aiAnalysis: {
      action: 'route_to_procurement',
      actionLabel: 'Route to Procurement Team',
      actionRationale: 'New vendor application from a credible supplier with enterprise references. Should be routed to the procurement/vendor management team with a standard onboarding pack.',
      suggestedResponse: "Thank you for your interest in partnering with Arcella! We've forwarded your inquiry to our Vendor Relations team who will reach out within 3–5 business days with our supplier onboarding documentation.",
      confidence: 0.91,
      flags: [],
    },
  },
  {
    id: 'ENQ-1005',
    senderType: 'customer',
    channel: 'email',
    status: 'open',
    priority: 'low',
    created: '2025-03-04T13:10:00',
    updated: '2025-03-04T13:10:00',
    subject: 'Question about product compatibility',
    preview: "Hey, I bought the Olight Warrior X flashlight last month and I'm wondering if the 18650 battery it comes with works with the Olight S2R charger I already own? I couldn't find this in the product description. Also do you stock replacement batteries for this model?",
    sender: {
      name: 'Tom Bergmann',
      email: 'tbergmann@outlook.com',
      phone: null,
      type: 'customer',
      tier: 'Bronze',
      ltv: '$210',
      totalOrders: 3,
    },
    intent: 'product_question',
    intentLabel: 'Product Question',
    urgency: 1,
    sentiment: 'neutral',
    sentimentScore: 0.05,
    tags: ['product-info', 'compatibility'],
    orderRef: null,
    assignedTo: null,
    resolution: null,
    aiAnalysis: null,
  },
  {
    id: 'ENQ-1006',
    senderType: 'customer',
    channel: 'voicemail',
    status: 'resolved',
    priority: 'medium',
    created: '2025-03-03T11:30:00',
    updated: '2025-03-03T14:20:00',
    subject: 'Voicemail: Request to update shipping address before dispatch',
    preview: "[Voicemail transcript] Hi, this is Elena Vasquez. I just placed order number 91105 this morning and I realised I put in the wrong shipping address — I need to change it to 1440 West Oak Street, Apt 7B, Chicago. Please can someone update this before it ships? Thank you.",
    sender: {
      name: 'Elena Vasquez',
      email: 'e.vasquez@mail.com',
      phone: null,
      type: 'customer',
      tier: 'Gold',
      ltv: '$3,100',
      totalOrders: 41,
    },
    intent: 'address_change',
    intentLabel: 'Address Change Request',
    urgency: 3,
    sentiment: 'concerned',
    sentimentScore: -0.3,
    tags: ['shipping', 'address-update', 'pre-dispatch'],
    orderRef: '#91105',
    assignedTo: 'Daphne K.',
    resolution: 'resolved_address_updated',
    aiAnalysis: {
      action: 'update_and_confirm',
      actionLabel: 'Update Address & Confirm',
      actionRationale: 'Gold customer requesting pre-dispatch address change. Time-sensitive — check fulfillment status before updating.',
      suggestedResponse: "Hi Elena, we've updated the shipping address on Order #91105 to 1440 West Oak Street, Apt 7B, Chicago. You'll receive an updated confirmation email shortly.",
      confidence: 0.96,
      flags: [{ label: 'Pre-dispatch window closing', severity: 'medium' }],
    },
  },
  {
    id: 'ENQ-1007',
    senderType: 'vendor',
    channel: 'email',
    status: 'escalated',
    priority: 'critical',
    created: '2025-03-03T09:00:00',
    updated: '2025-03-03T10:30:00',
    subject: 'Invoice dispute — payment 45 days overdue',
    preview: "I am writing on behalf of GlobalRose Floral Wholesale regarding invoice #GR-20250115 for $12,400 which has been outstanding for 45 days, significantly past your agreed NET-30 terms. We have sent three prior reminders without response. If payment is not received by March 10th, we will be forced to suspend supply and pursue collections.",
    sender: {
      name: 'Carlos Ibarra',
      email: 'c.ibarra@globalrosefloral.com',
      phone: '+1 (305) 555-0077',
      type: 'vendor',
      company: 'GlobalRose Floral Wholesale',
      tier: null,
      ltv: null,
      totalOrders: 0,
    },
    intent: 'payment_dispute',
    intentLabel: 'Payment Dispute',
    urgency: 5,
    sentiment: 'frustrated',
    sentimentScore: -0.79,
    tags: ['vendor', 'payment', 'legal-risk', 'supply-disruption'],
    orderRef: 'INV #GR-20250115',
    assignedTo: 'Daphne K.',
    resolution: null,
    escalationSignals: ['collections', 'supply_suspension', 'legal'],
    aiAnalysis: {
      action: 'escalate_finance',
      actionLabel: 'Escalate to Finance & Legal',
      actionRationale: 'Overdue vendor invoice with explicit legal and supply-disruption threats. Requires immediate escalation to finance team — do not respond with standard template.',
      suggestedResponse: null,
      confidence: 0.89,
      flags: [
        { label: 'Legal threat detected', severity: 'critical' },
        { label: 'Supply disruption risk', severity: 'high' },
      ],
    },
  },
  {
    id: 'ENQ-1008',
    senderType: 'customer',
    channel: 'email',
    status: 'open',
    priority: 'low',
    created: '2025-03-02T16:45:00',
    updated: '2025-03-02T16:45:00',
    subject: 'How do I cancel my Arcella Plus subscription?',
    preview: "Hi, I'd like to cancel my Arcella Plus subscription. I signed up during the Black Friday promo and have been charged $9.99/month since then. I haven't really been using the features. Can you cancel it and let me know if I'll get a partial refund for this month?",
    sender: {
      name: 'James Okafor',
      email: 'j.okafor@gmail.com',
      phone: null,
      type: 'customer',
      tier: 'Silver',
      ltv: '$560',
      totalOrders: 7,
    },
    intent: 'subscription_cancellation',
    intentLabel: 'Subscription Cancellation',
    urgency: 1,
    sentiment: 'neutral',
    sentimentScore: -0.1,
    tags: ['subscription', 'cancellation', 'churn-risk'],
    orderRef: null,
    assignedTo: null,
    resolution: null,
    aiAnalysis: null,
  },
];

// Intent colour mapping for badges
export const INTENT_COLORS = {
  order_status:              'blue',
  bulk_order_inquiry:        'amber',
  billing_dispute:           'red',
  vendor_onboarding:         'amber',
  product_question:          'blue',
  address_change:            'blue',
  payment_dispute:           'red',
  subscription_cancellation: 'orange',
};

// Resolution options specific to enquiry tickets
export const ENQUIRY_RESOLUTION_OPTIONS = [
  { id: 'replied',           label: 'Replied & Resolved',    icon: '✉', color: 'green',  desc: 'Sent a response that fully resolves the enquiry.' },
  { id: 'escalated_team',    label: 'Escalated to Team',     icon: '⬆', color: 'orange', desc: 'Forwarded to the appropriate internal team.' },
  { id: 'escalated_manager', label: 'Escalated to Manager',  icon: '⚑', color: 'red',    desc: 'Requires manager or senior agent review.' },
  { id: 'pending_info',      label: 'Awaiting Customer Info', icon: '?', color: 'amber',  desc: 'Replied and waiting for more information.' },
  { id: 'no_action',         label: 'No Action Required',    icon: '—', color: 'blue',   desc: 'Spam, duplicate, or out-of-scope enquiry.' },
  { id: 'resolved_internal', label: 'Resolved Internally',   icon: '✓', color: 'green',  desc: 'Handled internally without customer response needed.' },
];
