SELECT
    sr.SR_TICKET_NUMBER,
    sr.SR_RETURN_AMT,
    sr.SR_FEE,
    sr.SR_NET_LOSS,
    sr.SR_RETURN_QUANTITY,
    r.R_REASON_SK,
    r.R_REASON_ID,
    r.R_REASON_DESC,
    i.I_ITEM_SK,
    i.I_PRODUCT_NAME,
    i.I_CATEGORY,
    i.I_CATEGORY_FULL,
    i.I_CLASS,
    i.I_BRAND,
    i.I_CURRENT_PRICE,
    i.I_LIST_PRICE,
    i.I_ITEM_DESC,
    i.I_PRODUCT_URL,
    c.C_CUSTOMER_SK,
    c.C_FIRST_NAME,
    c.C_LAST_NAME,
    c.C_EMAIL_ADDRESS,
    c.C_PREFERRED_CUST_FLAG,
    d.D_DATE,
    COALESCE(sr.SR_STATUS, 'Open')   AS SR_STATUS,
    COALESCE(sr.SR_RESOLUTION, '')   AS SR_RESOLUTION,
    COALESCE(rc.RETURN_COUNT, 0)     AS CUSTOMER_ORDER_COUNT
FROM SYNTHETIC_COMPANYDB.COMPANY.STORE_RETURNS sr
    LEFT JOIN SYNTHETIC_COMPANYDB.COMPANY.REASON r
        ON r.R_REASON_SK = sr.SR_REASON_SK
    LEFT JOIN (
        SELECT *,
               ROW_NUMBER() OVER (ORDER BY I_ITEM_SK) AS I_RN
        FROM SYNTHETIC_COMPANYDB.COMPANY.ITEM
        WHERE I_AVAILABLE = TRUE
    ) i ON i.I_RN = sr.SR_ITEM_SK
    LEFT JOIN SYNTHETIC_COMPANYDB.COMPANY.CUSTOMER c
        ON c.C_CUSTOMER_SK = sr.SR_CUSTOMER_SK
    LEFT JOIN SYNTHETIC_COMPANYDB.COMPANY.DATE_DIM d
        ON d.D_DATE_SK = sr.SR_RETURNED_DATE_SK
    LEFT JOIN (
        SELECT SR_CUSTOMER_SK,
               COUNT(DISTINCT SR_TICKET_NUMBER) AS RETURN_COUNT
        FROM SYNTHETIC_COMPANYDB.COMPANY.STORE_RETURNS
        WHERE SR_CUSTOMER_SK IS NOT NULL
        GROUP BY SR_CUSTOMER_SK
    ) rc ON rc.SR_CUSTOMER_SK = sr.SR_CUSTOMER_SK
ORDER BY sr.SR_RETURNED_DATE_SK DESC, sr.SR_TICKET_NUMBER
LIMIT {limit} OFFSET {offset}