create or replace TABLE DASH_MCP_DB.DATA.FACT_TRANSACTIONS (
	TRANSACTION_ID VARCHAR(16777216),
	ACCOUNT_ID VARCHAR(16777216),
	CUSTOMER_ID VARCHAR(16777216),
	TRANSACTION_DATE TIMESTAMP_NTZ(9),
	TRANSACTION_TYPE VARCHAR(16777216),
	AMOUNT NUMBER(38,2),
	BALANCE_AFTER NUMBER(38,2),
	MERCHANT_NAME VARCHAR(16777216),
	MERCHANT_CATEGORY VARCHAR(16777216),
	CHANNEL VARCHAR(16777216),
	LOCATION VARCHAR(16777216),
	DESCRIPTION VARCHAR(16777216),
	IS_FLAGGED NUMBER(38,0),
	FRAUD_SCORE NUMBER(38,2)
);

create or replace TABLE DASH_MCP_DB.DATA.FACT_SUPPORT_TICKETS (
	TICKET_ID VARCHAR(11) NOT NULL,
	CUSTOMER_ID VARCHAR(10) NOT NULL,
	ACCOUNT_ID VARCHAR(10),
	CREATED_DATE DATE NOT NULL,
	GEO_ID VARCHAR(8),
	CATEGORY VARCHAR(30),
	SUBCATEGORY VARCHAR(50),
	PRIORITY VARCHAR(10),
	CHANNEL VARCHAR(20),
	SUBJECT VARCHAR(500),
	DESCRIPTION VARCHAR(1000),
	STATUS VARCHAR(20),
	ASSIGNED_AGENT VARCHAR(8),
	RESOLUTION_DATE DATE,
	RESOLUTION_TIME_HOURS NUMBER(8,2),
	SATISFACTION_SCORE NUMBER(1,0),
	FIRST_RESPONSE_TIME_MINUTES NUMBER(8,2),
	constraint PK_FACT_SUPPORT_TICKETS primary key (TICKET_ID),
	constraint FK_SUPPORT_CUSTOMER foreign key (CUSTOMER_ID) references DASH_MCP_DB.DATA.DIM_CUSTOMERS(CUSTOMER_ID)
);

create or replace TABLE DASH_MCP_DB.DATA.FACT_RISK_ASSESSMENTS (
	ASSESSMENT_ID VARCHAR(10) NOT NULL,
	CUSTOMER_ID VARCHAR(10) NOT NULL,
	ASSESSMENT_DATE DATE NOT NULL,
	CREDIT_RISK_SCORE NUMBER(5,2),
	FRAUD_RISK_SCORE NUMBER(5,2),
	AML_RISK_SCORE NUMBER(5,2),
	OVERALL_RISK_RATING VARCHAR(15),
	RISK_FACTORS VARCHAR(500),
	REVIEW_REQUIRED NUMBER(1,0) DEFAULT 0,
	LAST_REVIEW_DATE DATE,
	NEXT_REVIEW_DATE DATE,
	constraint PK_FACT_RISK_ASSESSMENTS primary key (ASSESSMENT_ID),
	constraint FK_RISK_CUSTOMER foreign key (CUSTOMER_ID) references DASH_MCP_DB.DATA.DIM_CUSTOMERS(CUSTOMER_ID)
);

create or replace TABLE DASH_MCP_DB.DATA.FACT_MARKETING_RESPONSES (
	RESPONSE_ID VARCHAR(12) NOT NULL,
	CUSTOMER_ID VARCHAR(10) NOT NULL,
	CAMPAIGN_ID VARCHAR(10) NOT NULL,
	CONTACTED_DATE DATE NOT NULL,
	GEO_ID VARCHAR(8),
	RESPONSE_TYPE VARCHAR(20),
	CONVERSION_VALUE NUMBER(10,2) DEFAULT 0,
	CHANNEL_USED VARCHAR(20),
	ENGAGEMENT_SCORE NUMBER(3,0),
	constraint PK_FACT_MARKETING_RESPONSES primary key (RESPONSE_ID),
	constraint FK_MKT_CUSTOMER foreign key (CUSTOMER_ID) references DASH_MCP_DB.DATA.DIM_CUSTOMERS(CUSTOMER_ID),
	constraint FK_MKT_CAMPAIGN foreign key (CAMPAIGN_ID) references DASH_MCP_DB.DATA.DIM_CAMPAIGNS(CAMPAIGN_ID)
);

create or replace TABLE DASH_MCP_DB.DATA.DIM_CUSTOMERS (
	CUSTOMER_ID VARCHAR(10) NOT NULL,
	FIRST_NAME VARCHAR(50) NOT NULL,
	LAST_NAME VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	PHONE VARCHAR(30),
	DATE_OF_BIRTH DATE,
	SSN_HASH VARCHAR(32),
	ADDRESS VARCHAR(200),
	CITY VARCHAR(50),
	STATE VARCHAR(2),
	ZIP_CODE VARCHAR(10),
	REGION VARCHAR(20),
	CUSTOMER_SEGMENT VARCHAR(20),
	CREDIT_SCORE NUMBER(3,0),
	ANNUAL_INCOME NUMBER(10,2),
	NET_WORTH NUMBER(12,2),
	JOIN_DATE DATE,
	STATUS VARCHAR(20),
	ACQUISITION_CHANNEL VARCHAR(30),
	LIFETIME_VALUE NUMBER(10,2),
	RISK_PROFILE VARCHAR(10),
	constraint UK_DIM_CUSTOMERS_EMAIL unique (EMAIL),
	constraint PK_DIM_CUSTOMERS primary key (CUSTOMER_ID)
);

create or replace TABLE DASH_MCP_DB.DATA.DIM_CAMPAIGNS (
	CAMPAIGN_ID VARCHAR(10) NOT NULL,
	CAMPAIGN_NAME VARCHAR(200) NOT NULL,
	CAMPAIGN_TYPE VARCHAR(20),
	OBJECTIVE VARCHAR(20),
	PRODUCT_PROMOTED VARCHAR(8),
	START_DATE DATE,
	END_DATE DATE,
	BUDGET NUMBER(12,2),
	ACTUAL_SPEND NUMBER(12,2),
	TARGET_AUDIENCE VARCHAR(20),
	TARGET_REGION VARCHAR(20),
	IMPRESSIONS NUMBER(10,0),
	CLICKS NUMBER(8,0),
	CONVERSIONS NUMBER(8,0),
	REVENUE_GENERATED NUMBER(12,2),
	ROI NUMBER(8,2),
	STATUS VARCHAR(20),
	constraint PK_DIM_CAMPAIGNS primary key (CAMPAIGN_ID)
);