create or replace TABLE SYNTHETIC_COMPANYDB.COMPANY.CUSTOMER (
	C_CUSTOMER_SK NUMBER(38,0) NOT NULL,
	C_FIRST_NAME VARCHAR(50),
	C_LAST_NAME VARCHAR(50),
	C_EMAIL_ADDRESS VARCHAR(100),
	C_PREFERRED_CUST_FLAG VARCHAR(1),
	primary key (C_CUSTOMER_SK)
)COMMENT='The table contains customer information. Each record represents a single customer and includes details about their name, contact information, and preferences.';

create or replace TABLE SYNTHETIC_COMPANYDB.COMPANY.STORE_SALES (
	SS_SOLD_DATE_SK NUMBER(38,0),
	SS_SOLD_TIME_SK NUMBER(38,0),
	SS_ITEM_SK NUMBER(38,0) NOT NULL,
	SS_CUSTOMER_SK NUMBER(38,0),
	SS_CDEMO_SK NUMBER(38,0),
	SS_HDEMO_SK NUMBER(38,0),
	SS_ADDR_SK NUMBER(38,0),
	SS_STORE_SK NUMBER(38,0),
	SS_PROMO_SK NUMBER(38,0),
	SS_TICKET_NUMBER NUMBER(38,0) NOT NULL,
	SS_QUANTITY NUMBER(38,0),
	SS_WHOLESALE_COST NUMBER(7,2),
	SS_LIST_PRICE NUMBER(7,2),
	SS_SALES_PRICE NUMBER(7,2),
	SS_EXT_DISCOUNT_AMT NUMBER(7,2),
	SS_EXT_SALES_PRICE NUMBER(7,2),
	SS_EXT_WHOLESALE_COST NUMBER(7,2),
	SS_EXT_LIST_PRICE NUMBER(7,2),
	SS_EXT_TAX NUMBER(7,2),
	SS_COUPON_AMT NUMBER(7,2),
	SS_NET_PAID NUMBER(7,2),
	SS_NET_PAID_INC_TAX NUMBER(7,2),
	SS_NET_PROFIT NUMBER(7,2),
	primary key (SS_ITEM_SK, SS_TICKET_NUMBER)
);


create or replace TABLE SYNTHETIC_COMPANYDB.COMPANY.DATE_DIM (
	D_DATE_SK NUMBER(38,0) NOT NULL,
	D_DATE DATE NOT NULL,
	primary key (D_DATE_SK)
);

create or replace TABLE SYNTHETIC_COMPANYDB.COMPANY.ITEM (
	I_ITEM_SK NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	I_ITEM_ID VARCHAR(50),
	I_PRODUCT_NAME VARCHAR(500),
	I_ITEM_DESC VARCHAR(16000),
	I_CURRENT_PRICE NUMBER(10,2),
	I_LIST_PRICE NUMBER(10,2),
	I_CATEGORY VARCHAR(100),
	I_CLASS VARCHAR(100),
	I_CATEGORY_FULL VARCHAR(500),
	I_BRAND VARCHAR(200),
	I_PRODUCT_URL VARCHAR(1000),
	I_GTIN VARCHAR(50),
	I_ITEM_NUMBER VARCHAR(50),
	I_PACKAGE_SIZE VARCHAR(200),
	I_AVAILABLE BOOLEAN,
	I_CRAWL_TIMESTAMP TIMESTAMP_NTZ(9),
	primary key (I_ITEM_SK)
)COMMENT='The table contains records of products, including their descriptions, pricing, and categorization. Each record represents a single item and includes details about its attributes, such as brand, category, and availability.'
;

create or replace TABLE SYNTHETIC_COMPANYDB.COMPANY.REASON (
	R_REASON_SK NUMBER(38,0) NOT NULL,
	R_REASON_ID VARCHAR(16) NOT NULL,
	R_REASON_DESC VARCHAR(100),
	primary key (R_REASON_SK)
);


create or replace TABLE SYNTHETIC_COMPANYDB.COMPANY.STORE_RETURNS (
	SR_TICKET_NUMBER NUMBER(38,0) NOT NULL,
	SR_RETURN_AMT NUMBER(7,2),
	SR_FEE NUMBER(7,2),
	SR_NET_LOSS NUMBER(7,2),
	SR_RETURN_QUANTITY NUMBER(38,0),
	SR_REASON_SK NUMBER(38,0),
	SR_CUSTOMER_SK NUMBER(38,0),
	SR_RETURNED_DATE_SK NUMBER(38,0),
	SR_ITEM_SK NUMBER(38,0),
	SR_STATUS VARCHAR(10) DEFAULT 'Open',
	SR_RESOLUTION VARCHAR(16000) DEFAULT 'Resolved',
	foreign key (SR_REASON_SK) references SYNTHETIC_COMPANYDB.COMPANY.REASON(R_REASON_SK),
	foreign key (SR_CUSTOMER_SK) references SYNTHETIC_COMPANYDB.COMPANY.CUSTOMER(C_CUSTOMER_SK),
	foreign key (SR_RETURNED_DATE_SK) references SYNTHETIC_COMPANYDB.COMPANY.DATE_DIM(D_DATE_SK)
);

create or replace TABLE SYNTHETIC_COMPANYDB.COMPANY.TICKET_STATUS_HISTORY (
	TSH_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	TSH_TICKET_NUMBER NUMBER(38,0) NOT NULL,
	TSH_OLD_STATUS VARCHAR(10),
	TSH_NEW_STATUS VARCHAR(10) NOT NULL,
	TSH_CHANGED_AT TIMESTAMP_NTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	TSH_CHANGED_BY VARCHAR(100) DEFAULT 'system',
	TSH_NOTE VARCHAR(500),
	primary key (TSH_ID)
)COMMENT='The table contains records of status changes for tickets. Each record represents a single status update and includes details about the old and new status, the user who made the change, and the timestamp of the change.'
;

create or replace TABLE SYNTHETIC_COMPANYDB.COMPANY.TICKET_STATUS_HISTORY (
	TSH_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	TSH_TICKET_NUMBER NUMBER(38,0) NOT NULL,
	TSH_OLD_STATUS VARCHAR(10),
	TSH_NEW_STATUS VARCHAR(10) NOT NULL,
	TSH_CHANGED_AT TIMESTAMP_NTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	TSH_CHANGED_BY VARCHAR(100) DEFAULT 'system',
	TSH_NOTE VARCHAR(500),
	primary key (TSH_ID)
)COMMENT='The table contains records of status changes for tickets. Each record represents a single status update and includes details about the old and new status, the user who made the change, and the timestamp of the change.'
;


create or replace TABLE SYNTHETIC_COMPANYDB.COMPANY.WALMART_CSV (
	UNIQ_ID VARCHAR(16777216),
	CRAWL_TIMESTAMP TIMESTAMP_NTZ(9),
	PRODUCT_URL VARCHAR(16777216),
	PRODUCT_NAME VARCHAR(16777216),
	DESCRIPTION VARCHAR(16777216),
	LIST_PRICE NUMBER(38,2),
	SALE_PRICE NUMBER(38,2),
	BRAND VARCHAR(16777216),
	ITEM_NUMBER VARCHAR(16777216),
	GTIN NUMBER(38,0),
	PACKAGE_SIZE VARCHAR(16777216),
	CATEGORY VARCHAR(16777216),
	POSTAL_CODE VARCHAR(16777216),
	AVAILABLE BOOLEAN
);