create or replace TABLE SYNTHETIC_COMPANYDB.COMPANY.CUSTOMER (
	C_CUSTOMER_SK NUMBER(38,0) NOT NULL,
	C_FIRST_NAME VARCHAR(50),
	C_LAST_NAME VARCHAR(50),
	C_EMAIL_ADDRESS VARCHAR(100),
	C_PREFERRED_CUST_FLAG VARCHAR(1),
	primary key (C_CUSTOMER_SK)
);
